### ISSUE TITLE
How to use this custom pwd hash

### ISSUE THREAD

**Issue by suanziliu** [pavelbogomolenko/keycloak-custom-password-hash#1]
hi @pavelbogomolenko 

Would you please provide how to use this custom pwd hash spi inside keycloak?

After build this project, how can I connected it with keycloak?

**Comment by pavelbogomolenko** [comment]
I havent looked into this project for a while, but as far as I remember, you just have to build this project (look into README) and this SPI will be "automatically" injected. Didnt it work out for you out of the box?

**Comment by suanziliu** [comment]
@pavelbogomolenko 
Thanks for your reply!

> Didnt it work out for you out of the box?

Unfortunately no.

I modified the source code of keycloak by adding a new MyHashProviderFactory as well as MyHashProvider.

As it depends on `org.apache.commons`, when running the packed distribution zip file, it always tell me `class not found exception(apache.commons)`.

So I'm wondering if modifying keycloak source code is not a good idea.

> you just have to build this project (look into README) and this SPI will be "automatically" injected

Can I ask after building this project, how to run keycloak then? Do you remember if it works while running the keycloak distribution ?

**Comment by pavelbogomolenko** [comment]
You dont have to modify source code of keycloak to make it work. Main idea of SPI is to override Service Provider Interface that is exposed by keycloak.

org.apache.commons (commons-codec) should be included in pom file https://github.com/pavelbogomolenko/keycloak-custom-password-hash/blob/master/pom.xml#L44

After building this project you will need to run generated *.jar file of keycloak.

**Comment by suanziliu** [comment]
Hi @pavelbogomolenko 

> After building this project you will need to run generated *.jar file of keycloak.

Can I ask how to run the generated password-hash-example.jar?

Actually, I follow this guide https://www.keycloak.org/docs/latest/server_development/index.html#implementing-an-spi

by adding this `password-hash-example.jar` to `~/Documents/keycloak-6.0.1/modules/`, but when running `./bin/standalone.sh`, it turns out to be: it cannot find `CustomPasswordHashProvider.java` inside this module

**Comment by suanziliu** [comment]
Hi @pavelbogomolenko 

I finally achieve it by following this guide https://www.keycloak.org/docs/latest/server_development/index.html#implementing-an-spi
by adding this `password-hash-example.jar` to ~/Documents/keycloak-6.0.1/modules/

By while starting keycloak by running `./bin/standalone.sh`, it shows me 
```
Caused by: org.keycloak.models.ModelException: Invalid config for hashAlgorithm: Password hashing provider not found
	at org.keycloak.models.PasswordPolicy$Builder.build(PasswordPolicy.java:181)
	at org.keycloak.models.PasswordPolicy.parse(PasswordPolicy.java:58)
	at org.keycloak.models.jpa.RealmAdapter.getPasswordPolicy(RealmAdapter.java:884)
	at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:204)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:399)
	at org.keycloak.services.managers.ApplianceBootstrap.isNewInstall(ApplianceBootstrap.java:46)
	at org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:212)
	at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:146)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:137)

```

Seems like the new hashPasswordProvider is not registered successfully. 
Did you ever met this?
